### ISSUE TITLE
normal users not able to add widget

### ISSUE THREAD

**Issue by merilturock** [iionly/au_sets#2]
Only the admin is able to add widgets while the normal users try to add a widget they get an error stating "We could not add your widget"

Thanking you 
meril

**Comment by iionly** [comment]
When I have created this repository here I was unaware that there was already an official repository existing (https://github.com/AU-Landing-Project/au_sets). The only purpose was getting AU Sets working on Elgg 1.9 (as it wasn't updated yet).

Now an updated version exists (https://elgg.org/plugins/1176403). Are you using this version? If not, could you try it? Maybe the bug you've found is already fixed.

**Comment by merilturock** [comment]
Thank you iionly i am using 1.12 elgg version & i am using the latest version 2.0.0 but i am having this problem.. Only the admin is able to add the widget i don't understand it ..

**Comment by iionly** [comment]
I'm sorry but I don't think I can be of much help here. The problem does not occur in the version of AU Sets hosted in this repo here but only in the newer version 2.0.0. Version 2.0.0 of AU Sets had come with a lot of code rework and I haven't figured out what exactly causes the problem with the adding of widgets for normal users. As I'm not using the AU Sets plugin myself actually I have not really much interest in spending time on fixing the issue in the official version of AU Sets.

I've opened an issue in the official AU Sets repo at https://github.com/AU-Landing-Project/au_sets/issues/10. Let's hope the bug gets fixed by the original developers.
